# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 683a12bebfbf42780a95e991d8c52003d946a99abd460ff51142463052422e31bd7dd987b976ba7db97db3561c432b4835c0f9ccd0aeb2ef91b60463766c3c6c

test:
  secret_key_base: 6501f86ee56dc11f668f7fca456a2eb8c42e47c44f79a049249fc11ea5bb0dc4d372b6258bbc52013d5b75fd9ac4014060a3ee802a1e73449e0dd2f98e6c8fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
